/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Ui23IdeModule extends AbstractUi23IdeModule {
}
