/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ui23.impl;

import dk.sdu.mmmi.mdsd.ui23.ui23.Label;
import dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Label</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LabelImpl extends ElementImpl implements Label
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LabelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Ui23Package.Literals.LABEL;
  }

} //LabelImpl
