/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ui23;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UI</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getTitle <em>Title</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getFunctions <em>Functions</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getForms <em>Forms</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getUI()
 * @model
 * @generated
 */
public interface UI extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getUI_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ui23.ui23.Function}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Functions</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getUI_Functions()
   * @model containment="true"
   * @generated
   */
  EList<Function> getFunctions();

  /**
   * Returns the value of the '<em><b>Forms</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ui23.ui23.Form}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forms</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getUI_Forms()
   * @model containment="true"
   * @generated
   */
  EList<Form> getForms();

} // UI
