/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ui23;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Factory
 * @model kind="package"
 * @generated
 */
public interface Ui23Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ui23";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mmmi/mdsd/ui23/Ui23";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ui23";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Ui23Package eINSTANCE = dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.UIImpl <em>UI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.UIImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getUI()
   * @generated
   */
  int UI = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI__TITLE = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI__FUNCTIONS = 1;

  /**
   * The feature id for the '<em><b>Forms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI__FORMS = 2;

  /**
   * The number of structural features of the '<em>UI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FunctionImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__TYPES = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormImpl <em>Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getForm()
   * @generated
   */
  int FORM = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__LAYOUT = 2;

  /**
   * The number of structural features of the '<em>Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ComponentImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 4;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LayoutImpl <em>Layout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LayoutImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLayout()
   * @generated
   */
  int LAYOUT = 3;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT__COMPONENTS = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Layout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ElementImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 5;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__EXP = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LabelImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLabel()
   * @generated
   */
  int LABEL = 6;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__EXP = ELEMENT__EXP;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.InputTextImpl <em>Input Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.InputTextImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getInputText()
   * @generated
   */
  int INPUT_TEXT = 7;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_TEXT__EXP = ELEMENT__EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_TEXT__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Input Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_TEXT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ButtonImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getButton()
   * @generated
   */
  int BUTTON = 8;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__EXP = ELEMENT__EXP;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormUseImpl <em>Form Use</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormUseImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getFormUse()
   * @generated
   */
  int FORM_USE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_USE__NAME = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_USE__EXP = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Form Use</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_USE_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ParameterImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__TYPE = 1;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ExpressionImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.TypeImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getType()
   * @generated
   */
  int TYPE = 11;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.BoolTypeImpl <em>Bool Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.BoolTypeImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getBoolType()
   * @generated
   */
  int BOOL_TYPE = 13;

  /**
   * The number of structural features of the '<em>Bool Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.StringTypeImpl <em>String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.StringTypeImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getStringType()
   * @generated
   */
  int STRING_TYPE = 14;

  /**
   * The number of structural features of the '<em>String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.NumberTypeImpl <em>Number Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.NumberTypeImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getNumberType()
   * @generated
   */
  int NUMBER_TYPE = 15;

  /**
   * The number of structural features of the '<em>Number Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.AndImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getAnd()
   * @generated
   */
  int AND = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.OrImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getOr()
   * @generated
   */
  int OR = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.EQImpl <em>EQ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.EQImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getEQ()
   * @generated
   */
  int EQ = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>EQ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.NEQImpl <em>NEQ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.NEQImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getNEQ()
   * @generated
   */
  int NEQ = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>NEQ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTImpl <em>LT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLT()
   * @generated
   */
  int LT = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTEImpl <em>LTE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTEImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLTE()
   * @generated
   */
  int LTE = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LTE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LTE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTImpl <em>GT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getGT()
   * @generated
   */
  int GT = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>GT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTEImpl <em>GTE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTEImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getGTE()
   * @generated
   */
  int GTE = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GTE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GTE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>GTE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GTE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ConcImpl <em>Conc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ConcImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getConc()
   * @generated
   */
  int CONC = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONC__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONC__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Conc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONC_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.PlusImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getPlus()
   * @generated
   */
  int PLUS = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.MinusImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getMinus()
   * @generated
   */
  int MINUS = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.MultImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getMult()
   * @generated
   */
  int MULT = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.DivImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getDiv()
   * @generated
   */
  int DIV = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueIntImpl <em>Value Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueIntImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getValueInt()
   * @generated
   */
  int VALUE_INT = 29;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_INT__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Value Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_INT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueStringImpl <em>Value String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueStringImpl
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getValueString()
   * @generated
   */
  int VALUE_STRING = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_STRING__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Value String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_STRING_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI <em>UI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>UI</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.UI
   * @generated
   */
  EClass getUI();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.UI#getTitle()
   * @see #getUI()
   * @generated
   */
  EAttribute getUI_Title();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.UI#getFunctions()
   * @see #getUI()
   * @generated
   */
  EReference getUI_Functions();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.mdsd.ui23.ui23.UI#getForms <em>Forms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Forms</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.UI#getForms()
   * @see #getUI()
   * @generated
   */
  EReference getUI_Forms();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Function#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Function#getTypes()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Types();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Form <em>Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Form
   * @generated
   */
  EClass getForm();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Form#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Form#getName()
   * @see #getForm()
   * @generated
   */
  EAttribute getForm_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Form#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Form#getParameters()
   * @see #getForm()
   * @generated
   */
  EReference getForm_Parameters();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Form#getLayout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Layout</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Form#getLayout()
   * @see #getForm()
   * @generated
   */
  EReference getForm_Layout();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Layout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Layout
   * @generated
   */
  EClass getLayout();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Layout#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Layout#getComponents()
   * @see #getLayout()
   * @generated
   */
  EReference getLayout_Components();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Element#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Element#getExp()
   * @see #getElement()
   * @generated
   */
  EReference getElement_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.InputText <em>Input Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Text</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.InputText
   * @generated
   */
  EClass getInputText();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.InputText#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.InputText#getName()
   * @see #getInputText()
   * @generated
   */
  EAttribute getInputText_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Button#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Button#getName()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.FormUse <em>Form Use</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Use</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.FormUse
   * @generated
   */
  EClass getFormUse();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.FormUse#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.FormUse#getName()
   * @see #getFormUse()
   * @generated
   */
  EAttribute getFormUse_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.FormUse#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.FormUse#getExp()
   * @see #getFormUse()
   * @generated
   */
  EReference getFormUse_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Parameter#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Parameter#getType()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Type();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.BoolType <em>Bool Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Type</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.BoolType
   * @generated
   */
  EClass getBoolType();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Type</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.StringType
   * @generated
   */
  EClass getStringType();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.NumberType <em>Number Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Type</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.NumberType
   * @generated
   */
  EClass getNumberType();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.EQ <em>EQ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EQ</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.EQ
   * @generated
   */
  EClass getEQ();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.EQ#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.EQ#getLeft()
   * @see #getEQ()
   * @generated
   */
  EReference getEQ_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.EQ#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.EQ#getRight()
   * @see #getEQ()
   * @generated
   */
  EReference getEQ_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.NEQ <em>NEQ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NEQ</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.NEQ
   * @generated
   */
  EClass getNEQ();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.NEQ#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.NEQ#getLeft()
   * @see #getNEQ()
   * @generated
   */
  EReference getNEQ_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.NEQ#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.NEQ#getRight()
   * @see #getNEQ()
   * @generated
   */
  EReference getNEQ_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LT <em>LT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LT</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LT
   * @generated
   */
  EClass getLT();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LT#getLeft()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LT#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LT#getRight()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LTE <em>LTE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LTE</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LTE
   * @generated
   */
  EClass getLTE();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LTE#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LTE#getLeft()
   * @see #getLTE()
   * @generated
   */
  EReference getLTE_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.LTE#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.LTE#getRight()
   * @see #getLTE()
   * @generated
   */
  EReference getLTE_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GT <em>GT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GT</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GT
   * @generated
   */
  EClass getGT();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GT#getLeft()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GT#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GT#getRight()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GTE <em>GTE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GTE</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GTE
   * @generated
   */
  EClass getGTE();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GTE#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GTE#getLeft()
   * @see #getGTE()
   * @generated
   */
  EReference getGTE_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.GTE#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.GTE#getRight()
   * @see #getGTE()
   * @generated
   */
  EReference getGTE_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Conc <em>Conc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conc</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Conc
   * @generated
   */
  EClass getConc();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Conc#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Conc#getLeft()
   * @see #getConc()
   * @generated
   */
  EReference getConc_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Conc#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Conc#getRight()
   * @see #getConc()
   * @generated
   */
  EReference getConc_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Mult#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Mult#getLeft()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Mult#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Mult#getRight()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Div#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Div#getLeft()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.mdsd.ui23.ui23.Div#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Div#getRight()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueInt <em>Value Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Int</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.ValueInt
   * @generated
   */
  EClass getValueInt();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueInt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.ValueInt#getValue()
   * @see #getValueInt()
   * @generated
   */
  EAttribute getValueInt_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueString <em>Value String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value String</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.ValueString
   * @generated
   */
  EClass getValueString();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueString#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.ValueString#getValue()
   * @see #getValueString()
   * @generated
   */
  EAttribute getValueString_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Ui23Factory getUi23Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.UIImpl <em>UI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.UIImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getUI()
     * @generated
     */
    EClass UI = eINSTANCE.getUI();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UI__TITLE = eINSTANCE.getUI_Title();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI__FUNCTIONS = eINSTANCE.getUI_Functions();

    /**
     * The meta object literal for the '<em><b>Forms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI__FORMS = eINSTANCE.getUI_Forms();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FunctionImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__TYPES = eINSTANCE.getFunction_Types();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormImpl <em>Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getForm()
     * @generated
     */
    EClass FORM = eINSTANCE.getForm();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM__NAME = eINSTANCE.getForm_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM__PARAMETERS = eINSTANCE.getForm_Parameters();

    /**
     * The meta object literal for the '<em><b>Layout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM__LAYOUT = eINSTANCE.getForm_Layout();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LayoutImpl <em>Layout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LayoutImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLayout()
     * @generated
     */
    EClass LAYOUT = eINSTANCE.getLayout();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT__COMPONENTS = eINSTANCE.getLayout_Components();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ComponentImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ElementImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__EXP = eINSTANCE.getElement_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LabelImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.InputTextImpl <em>Input Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.InputTextImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getInputText()
     * @generated
     */
    EClass INPUT_TEXT = eINSTANCE.getInputText();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_TEXT__NAME = eINSTANCE.getInputText_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ButtonImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__NAME = eINSTANCE.getButton_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormUseImpl <em>Form Use</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.FormUseImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getFormUse()
     * @generated
     */
    EClass FORM_USE = eINSTANCE.getFormUse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_USE__NAME = eINSTANCE.getFormUse_Name();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM_USE__EXP = eINSTANCE.getFormUse_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ParameterImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__TYPE = eINSTANCE.getParameter_Type();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.TypeImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ExpressionImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.BoolTypeImpl <em>Bool Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.BoolTypeImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getBoolType()
     * @generated
     */
    EClass BOOL_TYPE = eINSTANCE.getBoolType();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.StringTypeImpl <em>String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.StringTypeImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getStringType()
     * @generated
     */
    EClass STRING_TYPE = eINSTANCE.getStringType();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.NumberTypeImpl <em>Number Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.NumberTypeImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getNumberType()
     * @generated
     */
    EClass NUMBER_TYPE = eINSTANCE.getNumberType();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.AndImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.OrImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.EQImpl <em>EQ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.EQImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getEQ()
     * @generated
     */
    EClass EQ = eINSTANCE.getEQ();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQ__LEFT = eINSTANCE.getEQ_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQ__RIGHT = eINSTANCE.getEQ_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.NEQImpl <em>NEQ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.NEQImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getNEQ()
     * @generated
     */
    EClass NEQ = eINSTANCE.getNEQ();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEQ__LEFT = eINSTANCE.getNEQ_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEQ__RIGHT = eINSTANCE.getNEQ_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTImpl <em>LT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLT()
     * @generated
     */
    EClass LT = eINSTANCE.getLT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__LEFT = eINSTANCE.getLT_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__RIGHT = eINSTANCE.getLT_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTEImpl <em>LTE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.LTEImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getLTE()
     * @generated
     */
    EClass LTE = eINSTANCE.getLTE();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTE__LEFT = eINSTANCE.getLTE_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LTE__RIGHT = eINSTANCE.getLTE_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTImpl <em>GT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getGT()
     * @generated
     */
    EClass GT = eINSTANCE.getGT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__LEFT = eINSTANCE.getGT_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__RIGHT = eINSTANCE.getGT_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTEImpl <em>GTE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.GTEImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getGTE()
     * @generated
     */
    EClass GTE = eINSTANCE.getGTE();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GTE__LEFT = eINSTANCE.getGTE_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GTE__RIGHT = eINSTANCE.getGTE_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ConcImpl <em>Conc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ConcImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getConc()
     * @generated
     */
    EClass CONC = eINSTANCE.getConc();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONC__LEFT = eINSTANCE.getConc_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONC__RIGHT = eINSTANCE.getConc_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.PlusImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.MinusImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.MultImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__LEFT = eINSTANCE.getMult_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__RIGHT = eINSTANCE.getMult_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.DivImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__LEFT = eINSTANCE.getDiv_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueIntImpl <em>Value Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueIntImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getValueInt()
     * @generated
     */
    EClass VALUE_INT = eINSTANCE.getValueInt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE_INT__VALUE = eINSTANCE.getValueInt_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueStringImpl <em>Value String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.ValueStringImpl
     * @see dk.sdu.mmmi.mdsd.ui23.ui23.impl.Ui23PackageImpl#getValueString()
     * @generated
     */
    EClass VALUE_STRING = eINSTANCE.getValueString();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE_STRING__VALUE = eINSTANCE.getValueString_Value();

  }

} //Ui23Package
