/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ui23;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueString#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getValueString()
 * @model
 * @generated
 */
public interface ValueString extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see dk.sdu.mmmi.mdsd.ui23.ui23.Ui23Package#getValueString_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.ui23.ui23.ValueString#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ValueString
