/*
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ui;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.ui23.ui.internal.Ui23Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Ui23ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Ui23Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Ui23Activator activator = Ui23Activator.getInstance();
		return activator != null ? activator.getInjector(Ui23Activator.DK_SDU_MMMI_MDSD_UI23_UI23) : null;
	}

}
