/**
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterators;
import dk.sdu.mmmi.mdsd.ui23.ui23.Button;
import dk.sdu.mmmi.mdsd.ui23.ui23.Component;
import dk.sdu.mmmi.mdsd.ui23.ui23.Div;
import dk.sdu.mmmi.mdsd.ui23.ui23.Element;
import dk.sdu.mmmi.mdsd.ui23.ui23.Expression;
import dk.sdu.mmmi.mdsd.ui23.ui23.Form;
import dk.sdu.mmmi.mdsd.ui23.ui23.FormUse;
import dk.sdu.mmmi.mdsd.ui23.ui23.InputText;
import dk.sdu.mmmi.mdsd.ui23.ui23.Label;
import dk.sdu.mmmi.mdsd.ui23.ui23.Layout;
import dk.sdu.mmmi.mdsd.ui23.ui23.Minus;
import dk.sdu.mmmi.mdsd.ui23.ui23.Mult;
import dk.sdu.mmmi.mdsd.ui23.ui23.Plus;
import dk.sdu.mmmi.mdsd.ui23.ui23.UI;
import dk.sdu.mmmi.mdsd.ui23.ui23.ValueInt;
import dk.sdu.mmmi.mdsd.ui23.ui23.ValueString;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class Ui23Generator extends AbstractGenerator {
  private static Map<String, String> variables;

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    HashMap<String, String> _hashMap = new HashMap<String, String>();
    Ui23Generator.variables = _hashMap;
    final UI ui = Iterators.<UI>filter(resource.getAllContents(), UI.class).next();
    String _lowerCase = ui.getTitle().toString().toLowerCase();
    String _plus = (_lowerCase + "/UserInterface");
    String _plus_1 = (_plus + ".java");
    fsa.generateFile(_plus_1, this.compileUserInterface(ui));
    String _lowerCase_1 = ui.getTitle().toString().toLowerCase();
    String _plus_2 = (_lowerCase_1 + "/BasicForm");
    String _plus_3 = (_plus_2 + ".java");
    fsa.generateFile(_plus_3, this.compileBasicForm(ui));
    fsa.generateFile((("common" + "/Form") + ".java"), this.compileCommonForm(ui));
  }

  /**
   * title Basic
   * 
   * form Basic {
   * column {
   * label : "My first form"
   * }
   * }
   */
  public CharSequence compileUserInterface(final UI ui) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package user_interface.");
    String _lowerCase = ui.getTitle().toString().toLowerCase();
    _builder.append(_lowerCase);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("import javax.swing.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class UserInterface{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public JFrame frame;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void open() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("frame = new JFrame(\"");
    String _title = ui.getTitle();
    _builder.append(_title, "\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("BasicForm form = new BasicForm(this);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("frame.add(form.createPanel());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("frame.pack();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("frame.setVisible(true);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public CharSequence compileBasicForm(final UI ui) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package user_interface.");
    String _lowerCase = ui.getTitle().toString().toLowerCase();
    _builder.append(_lowerCase);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("import javax.swing.*;");
    _builder.newLine();
    _builder.append("import java.awt.event.*;");
    _builder.newLine();
    _builder.append("import user_interface.common.*;");
    _builder.newLine();
    {
      EList<Form> _forms = ui.getForms();
      for(final Form form : _forms) {
        _builder.newLine();
        _builder.append("public class BasicForm extends Form{");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("UserInterface parent;");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("BasicForm(UserInterface parent) {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("this.parent = parent;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public JPanel createPanel(){");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("return createPanel1();");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public JPanel createPanel1() {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("JPanel panel = new JPanel();");
        _builder.newLine();
        _builder.append("\t\t");
        CharSequence _generateLayout = this.generateLayout(form.getLayout());
        _builder.append(_generateLayout, "\t\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("return panel;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public boolean checkValidity(){");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("return true;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder;
  }

  public CharSequence compileCommonForm(final UI ui) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package user_interface.common;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.swing.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public abstract class Form{");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public abstract boolean checkValidity();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public abstract JPanel createPanel();");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public CharSequence generateLayout(final Layout layout) {
    StringConcatenation _builder = new StringConcatenation();
    {
      String _name = layout.getName();
      boolean _equals = Objects.equal(_name, "row");
      if (_equals) {
        _builder.append("panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));");
        _builder.newLine();
      }
    }
    {
      String _name_1 = layout.getName();
      boolean _equals_1 = Objects.equal(_name_1, "column");
      if (_equals_1) {
        _builder.append("panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));");
        _builder.newLine();
      }
    }
    {
      EList<Component> _components = layout.getComponents();
      for(final Component component : _components) {
        Object _generateComponent = this.generateComponent(component);
        _builder.append(_generateComponent);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected Object _generateComponent(final Layout layout) {
    return this.generateLayout(layout);
  }

  protected Object _generateComponent(final Element element) {
    return this.generateElement(element);
  }

  protected Object _generateComponent(final FormUse formUse) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("panel.add(new JLabel(\"My first form\"));");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _generateElement(final Label label) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("panel.add(new JLabel(\"");
    String _computeExpression = Ui23Generator.computeExpression(label.getExpression());
    _builder.append(_computeExpression);
    _builder.append("\"));");
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _generateElement(final InputText inputText) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _generateElement(final Button button) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("\t");
    _builder.newLine();
    return _builder;
  }

  protected static String _computeExpression(final ValueInt exp) {
    return Integer.valueOf(exp.getValue()).toString();
  }

  protected static String _computeExpression(final ValueString exp) {
    return exp.getValue();
  }

  protected static String _computeExpression(final Plus exp) {
    String _computeExpression = Ui23Generator.computeExpression(exp.getLeft());
    String _plus = ("(" + _computeExpression);
    String _plus_1 = (_plus + "+");
    String _computeExpression_1 = Ui23Generator.computeExpression(exp.getRight());
    String _plus_2 = (_plus_1 + _computeExpression_1);
    return (_plus_2 + ")");
  }

  protected static String _computeExpression(final Minus exp) {
    String _computeExpression = Ui23Generator.computeExpression(exp.getLeft());
    String _plus = ("(" + _computeExpression);
    String _plus_1 = (_plus + "-");
    String _computeExpression_1 = Ui23Generator.computeExpression(exp.getRight());
    String _plus_2 = (_plus_1 + _computeExpression_1);
    return (_plus_2 + ")");
  }

  protected static String _computeExpression(final Mult exp) {
    String _computeExpression = Ui23Generator.computeExpression(exp.getLeft());
    String _plus = ("(" + _computeExpression);
    String _plus_1 = (_plus + "*");
    String _computeExpression_1 = Ui23Generator.computeExpression(exp.getRight());
    String _plus_2 = (_plus_1 + _computeExpression_1);
    return (_plus_2 + ")");
  }

  protected static String _computeExpression(final Div exp) {
    String _computeExpression = Ui23Generator.computeExpression(exp.getLeft());
    String _plus = ("(" + _computeExpression);
    String _plus_1 = (_plus + "/");
    String _computeExpression_1 = Ui23Generator.computeExpression(exp.getRight());
    String _plus_2 = (_plus_1 + _computeExpression_1);
    return (_plus_2 + ")");
  }

  public Object generateComponent(final Component element) {
    if (element instanceof Element) {
      return _generateComponent((Element)element);
    } else if (element instanceof FormUse) {
      return _generateComponent((FormUse)element);
    } else if (element instanceof Layout) {
      return _generateComponent((Layout)element);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(element).toString());
    }
  }

  public CharSequence generateElement(final Element button) {
    if (button instanceof Button) {
      return _generateElement((Button)button);
    } else if (button instanceof InputText) {
      return _generateElement((InputText)button);
    } else if (button instanceof Label) {
      return _generateElement((Label)button);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(button).toString());
    }
  }

  public static String computeExpression(final Expression exp) {
    if (exp instanceof Div) {
      return _computeExpression((Div)exp);
    } else if (exp instanceof Minus) {
      return _computeExpression((Minus)exp);
    } else if (exp instanceof Mult) {
      return _computeExpression((Mult)exp);
    } else if (exp instanceof Plus) {
      return _computeExpression((Plus)exp);
    } else if (exp instanceof ValueInt) {
      return _computeExpression((ValueInt)exp);
    } else if (exp instanceof ValueString) {
      return _computeExpression((ValueString)exp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp).toString());
    }
  }
}
