/*
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import dk.sdu.mmmi.mdsd.ui23.ui23.UI
import org.eclipse.xtext.xbase.testing.CompilationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(Ui23InjectorProvider)

class Ui23GenerationTest {
	@Inject	extension CompilationTestHelper
	
	@Test
	def void loadModel1() {
		'''
			title Basic
			
			form Basic {
				column {
					label : "My first form"
				}
			}
		'''.assertCompilesTo(
			'''
			MULTIPLE FILES WERE GENERATED
			
			File 1 : /myProject/./src-gen/Basic/BasicForm.java
			
			package user_interface.basic;
					
			import javax.swing.*;
			import java.awt.event.*;
			import user_interface.common.*;
			
			public class BasicForm extends Form{
			
				UserInterface parent;
				
				BasicForm(UserInterface parent) {
					this.parent = parent;
				}
			
				public JPanel createPanel(){
					return createPanel1();
				}
			
				public JPanel createPanel1() {
					JPanel panel = new JPanel();
					panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
					panel.add(new JLabel("My first form"));
					return panel;
				}
			
				public boolean checkValidity(){
					return true;
				}
			}
			
			File 2 : /myProject/./src-gen/Basic/UserInterface.java
			
			package user_interface.basic;
				
			import javax.swing.*;
			
			public class UserInterface{
				public JFrame frame;
			
				public void open() {
					frame = new JFrame("Basic");
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					BasicForm form = new BasicForm(this);
					frame.add(form.createPanel());
					frame.pack();
					frame.setVisible(true);
				}
			}
			
			File 3 : /myProject/./src-gen/common/Form.java
			
			package user_interface.common;
			
			import javax.swing.*;
			
			public abstract class Form{
				public abstract boolean checkValidity();
				public abstract JPanel createPanel();
			}
			
'''
		)
	}
}
