/*
 * generated by Xtext 2.34.0
 */
package dk.sdu.mmmi.mdsd.ui23.ide

import com.google.inject.Guice
import dk.sdu.mmmi.mdsd.ui23.Ui23RuntimeModule
import dk.sdu.mmmi.mdsd.ui23.Ui23StandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Ui23IdeSetup extends Ui23StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Ui23RuntimeModule, new Ui23IdeModule))
	}
	
}
